In [1]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [2]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    'aluno_id': [1, 2, 3, 4, 5, 6, 7, 8],
    'idade': [18, 22, 35, 19, 28, 45, 21, 30],
    'nota_media': [8.5, 4.2, 7.0, 3.1, 9.0, 6.5, 2.8, 7.8],
    'faltas': [2, 20, 5, 30, 1, 8, 35, 4],
    'evadiu': [0, 1, 0, 1, 0, 0, 1, 0]
}

df = pd.DataFrame(data)

In [5]:
df.head()

   aluno_id  idade  nota_media  faltas  evadiu
0         1     18         8.5       2       0
1         2     22         4.2      20       1
2         3     35         7.0       5       0
3         4     19         3.1      30       1
4         5     28         9.0       1       0

In [6]:
df.shape

(8, 5)

In [7]:
df.describe()

       aluno_id      idade  nota_media    faltas    evadiu
count   8.00000   8.000000    8.000000   8.00000  8.000000
mean    4.50000  27.250000    6.112500  13.12500  0.375000
std     2.44949   9.285165    2.435709  13.39976  0.517549
min     1.00000  18.000000    2.800000   1.00000  0.000000
25%     2.75000  20.500000    3.925000   3.50000  0.000000
50%     4.50000  25.000000    6.750000   6.50000  0.000000
75%     6.25000  31.250000    7.975000  22.50000  1.000000
max     8.00000  45.000000    9.000000  35.00000  1.000000

In [39]:
scaler = MinMaxScaler()

In [41]:
df_minmax = df.drop(['aluno_id','evadiu'],axis=1)

In [42]:
df_minmax

   idade  nota_media  faltas
0     18         8.5       2
1     22         4.2      20
2     35         7.0       5
3     19         3.1      30
4     28         9.0       1
5     45         6.5       8
6     21         2.8      35
7     30         7.8       4

In [46]:
df_minmax_scaled = scaler.fit_transform(df_minmax)
df_minmax_scaled = pd.DataFrame(df_minmax_scaled, columns=df_minmax.columns)

In [47]:
df_minmax_scaled

      idade  nota_media    faltas
0  0.000000    0.919355  0.029412
1  0.148148    0.225806  0.558824
2  0.629630    0.677419  0.117647
3  0.037037    0.048387  0.852941
4  0.370370    1.000000  0.000000
5  1.000000    0.596774  0.205882
6  0.111111    0.000000  1.000000
7  0.444444    0.806452  0.088235

In [50]:
scaler_2= StandardScaler()

In [55]:
df_standard = df.drop(['aluno_id','evadiu'],axis=1)
df_standard_scaled = scaler_2.fit_transform(df_standard)
df_standard_scaled = pd.DataFrame(df_standard_scaled, columns = df_standard.columns)

In [56]:
df_standard_scaled

      idade  nota_media    faltas
0 -1.064996    1.047886 -0.887563
1 -0.604457   -0.839406  0.548494
2  0.892294    0.389528 -0.648220
3 -0.949862   -1.322201  1.346303
4  0.086351    1.267338 -0.967343
5  2.043642    0.170076 -0.408877
6 -0.719592   -1.453873  1.745207
7  0.316621    0.740652 -0.728001

In [57]:
print("=== Min-Max Scaler ===")
print(df_minmax_scaled.describe().round(2))

print("\n=== Standard Scaler ===")
print(df_standard_scaled.describe().round(2))

=== Min-Max Scaler ===
       idade  nota_media  faltas
count   8.00        8.00    8.00
mean    0.34        0.53    0.36
std     0.34        0.39    0.39
min     0.00        0.00    0.00
25%     0.09        0.18    0.07
50%     0.26        0.64    0.16
75%     0.49        0.83    0.63
max     1.00        1.00    1.00

=== Standard Scaler ===
       idade  nota_media  faltas
count   8.00        8.00    8.00
mean   -0.00        0.00   -0.00
std     1.07        1.07    1.07
min    -1.06       -1.45   -0.97
25%    -0.78       -0.96   -0.77
50%    -0.26        0.28   -0.53
75%     0.46        0.82    0.75
max     2.04        1.27    1.75